//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.13
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 1d5f4f28-8602-4eff-a292-199043f31aba aws-my-sample-app-android-v0.13";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:14f6525d-a10c-43a3-80f6-49048815cf17";
    // Google Client ID for Web application
    public static final String GOOGLE_CLIENT_ID =
        "413451298336-jv66f1f3jahos0uvagaqchm77bqh0op6.apps.googleusercontent.com";
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-west-2");
}
